// Complete and Accurate Lipa City Barangays (72 total)
export const LIPA_BARANGAYS = [
  'Adya',
  'Anilao',
  'Anilao-Labac',
  'Antipolo Del Norte',
  'Antipolo Del Sur',
  'Bagong Pook',
  'Balintawak',
  'Banaybanay',
  'Bolbok',
  'Bugtong na Pulo',
  'Bulacnin',
  'Bulaklakan',
  'Calamias',
  'Cumba',
  'Dagatan',
  'Duhatan',
  'Halang',
  'Inosluban',
  'Kayumanggi',
  'Labac',
  'Latag',
  'Lodlod',
  'Lumbang',
  'Mabini',
  'Mataas na Lupa',
  'Malagonlong',
  'Malitlit',
  'Marawoy',
  'Munting Pulo',
  'Pagolingin Bata',
  'Pagolingin East',
  'Pagolingin West',
  'Pangao',
  'Pinagkawitan',
  'Pinagtongulan',
  'Plaridel',
  'Poblacion Barangay 1',
  'Poblacion Barangay 2',
  'Poblacion Barangay 3',
  'Poblacion Barangay 4',
  'Poblacion Barangay 5',
  'Poblacion Barangay 6',
  'Poblacion Barangay 7',
  'Poblacion Barangay 8',
  'Poblacion Barangay 9',
  'Poblacion Barangay 9-A',
  'Poblacion Barangay 10',
  'Poblacion Barangay 11',
  'Poblacion Barangay 12',
  'Pusil',
  'Quezon',
  'Rizal',
  'Sabang',
  'Sampaguita',
  'San Benito',
  'San Carlos',
  'San Celestino',
  'San Francisco',
  'San Guillermo',
  'San Isidro',
  'San Jose',
  'San Lucas',
  'San Salvador',
  'San Sebastian',
  'Santo Niño',
  'Santo Toribio',
  'Sico',
  'Talisay',
  'Tambo',
  'Tangob',
  'Tangway',
  'Tibig'
] as const

// Barangay coordinates for heatmap (approximate center coordinates)
export const LIPA_BARANGAY_COORDINATES = {
  'Adya': { lat: 13.8814827, lng: 121.1342373, zoom: 15 },
  'Anilao': { lat: 13.9014692, lng: 121.1716944, zoom: 15 },
  'Anilao-Labac': { lat: 13.8861132, lng: 121.1864558, zoom: 15 },
  'Antipolo del Norte': { lat: 13.9316385, lng: 121.1670943, zoom: 15 },
  'Antipolo del Sur': { lat: 13.9119193, lng: 121.1864893, zoom: 15 },

  'Bagong Pook': { lat: 13.9423, lng: 121.1103, zoom: 15 },
  'Balintawak': { lat: 13.9538067, lng: 121.1584888, zoom: 15 },
  'Banaybanay': { lat: 13.8970, lng: 121.2172, zoom: 15 },
  'Barangay 12': { lat: 13.761003, lng: 121.055566, zoom: 15 },
  'Bolbok': { lat: 13.9238285, lng: 121.1487819, zoom: 15 },

  'Bugtong na Pulo': { lat: 14.0000, lng: 121.1670, zoom: 15 },
  'Bulacnin': { lat: 13.9854, lng: 121.1414, zoom: 15 },
  'Bulaklakan': { lat: 13.9424, lng: 121.0978, zoom: 15 },
  'Calamias': { lat: 13.8606, lng: 121.1467, zoom: 15 },
  'Cumba': { lat: 13.9708, lng: 120.6584, zoom: 15 },
  'Dagatan': { lat: 13.9414, lng: 121.1642, zoom: 15 },
  
  'Duhatan': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Halang': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Inosloban': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Kayumanggi': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Latag': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Lodlod': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Lumbang': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Mabini': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Malagonlong': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Malitlit': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Marauoy': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Mataas na Lupa': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Munting Pulo': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pagolingin Bata': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pagolingin East': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pagolingin West': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pangao': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pinagkawitan': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pinagtongulan': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Plaridel': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 1': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 10': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 11': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 2': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 3': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 4': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 5': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 6': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 7': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 8': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 9': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Poblacion Barangay 9-A': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Pusil': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Quezon': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Rizal': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Sabang': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Sampaguita': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Benito': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Carlos': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Celestino': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Francisco': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Guillermo': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Jose': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Lucas': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Salvador': { /* lat: ?, lng: ?, zoom: 15 */ },
  'San Sebastian': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Santo Niño': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Santo Toribio': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Sapac': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Sico': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Talisay': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Tambo': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Tangob': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Tanguay': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Tibig': { /* lat: ?, lng: ?, zoom: 15 */ },
  'Tipacan': { /* lat: ?, lng: ?, zoom: 15 */ }
} as const
